version: "3.8"
services:
  pytorch-jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
    volumes:
      - .:/workspace/notebooks
      - ~/.cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
